---
# Create root CA private key and crt
# https://docs.ansible.com/ansible/latest/modules/openssl_privatekey_module.html#openssl-privatekey-module - module "openssl_privatekey"
# https://docs.ansible.com/ansible/latest/modules/openssl_csr_module.html#openssl-csr-module - module "openssl_csr"


- name: "Create root CA key"
  # delegate_to: localhost
  # module: openssl_privatekey
  openssl_privatekey:
          force: "{{ force_regeneration }}"
          mode: 0640
          path: "{{ cert_dir }}/{{ root_ca_name }}.key"
          size: 2048
          state: present
          type: "RSA"

- name: "Create CSR request"
  # delegate_to: localhost
  # module: openssl_csr
  openssl_csr:
          common_name: "{{ server_url }}"
          country_name: "{{ cert_country }}"
          email_address: "{{ ca_cert_email_address }}"
          force: "{{ force_regeneration }}"
          locality_name: "{{ cert_locality }}"
          mode: 0640
          organization_name: "{{ cert_organization }}"
          organizational_unit_name: "{{ ca_cert_organizational_unit }}"
          path: "{{ cert_dir }}/{{ root_ca_name }}.csr"
          privatekey_passphrase: "{{ cert_passphrase }}"
          privatekey_path: "{{ cert_dir }}/{{ root_ca_name }}.key"
          state: present
          state_or_province_name: "{{ cert_state }}"

- name: "Create root CA certificate" 
  # delegate_to: localhost
  # module: openssl_certificate
  openssl_certificate:
          privatekey_path: "{{ cert_dir }}/{{ root_ca_name }}.key"
          csr_path: "{{ cert_dir }}/{{ root_ca_name }}.csr"
          force: "{{ force_regeneration }}"
          path: "{{ cert_dir }}/{{ root_ca_name }}.crt"
          privatekey_passphrase: "{{ cert_passphrase }}"
          provider: "selfsigned"
          selfsigned_digest: "sha256"
          state: present
          
