---
# Create root CA private key and csr
# https://docs.ansible.com/ansible/latest/modules/openssl_privatekey_module.html#openssl-privatekey-module - module "openssl_privatekey"
# https://docs.ansible.com/ansible/latest/modules/openssl_csr_module.html#openssl-csr-module - module "openssl_csr"


- name: "Create private key"
  # local_action:
  # module: openssl_privatekey
  openssl_privatekey:
          force: "{{ force_regeneration }}"
          mode: 0640
          path: "{{ cert_dir }}/{{ server_name }}_private.key"
          size: 2048
          state: present
          type: "RSA"

- name: "Create CSR"
  # local_action:
  # module: openssl_csr
  openssl_csr:
          common_name: "{{ server_url }}"
          country_name: "{{ cert_country }}"
          email_address: "{{ cert_email_address }}"
          force: "{{ force_regeneration }}"
          locality_name: "{{ cert_locality }}"
          mode: 0640
          organization_name: "{{ cert_organization }}"
          organizational_unit_name: "{{ cert_organizational_unit }}"
          path: "{{ cert_dir }}/{{ server_name }}.csr"
          privatekey_passphrase: "{{ cert_passphrase }}"
          privatekey_path: "{{ cert_dir }}/{{ server_name }}_private.key"
          state: present
          state_or_province_name: "{{ cert_state }}"
          
